// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO1I_8iOYD8820Drj31Ks3pmUTEQ3S43k',
    appId: '1:422371067726:web:cafc3b498753a9e6ed001f',
    messagingSenderId: '422371067726',
    projectId: 'earthquakealert-8923c',
    authDomain: 'earthquakealert-8923c.firebaseapp.com',
    databaseURL: 'https://earthquakealert-8923c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'earthquakealert-8923c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdM6k7J49LjEWTmya5fsZIRMdv6SbDlu8',
    appId: '1:422371067726:android:d02cbf3312cede4bed001f',
    messagingSenderId: '422371067726',
    projectId: 'earthquakealert-8923c',
    databaseURL: 'https://earthquakealert-8923c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'earthquakealert-8923c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV0KR2TPvVzbwcbNz_YAtHOY1IRIrFjn4',
    appId: '1:422371067726:ios:159dc5102a723dc4ed001f',
    messagingSenderId: '422371067726',
    projectId: 'earthquakealert-8923c',
    databaseURL: 'https://earthquakealert-8923c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'earthquakealert-8923c.firebasestorage.app',
    iosBundleId: 'com.example.geoalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV0KR2TPvVzbwcbNz_YAtHOY1IRIrFjn4',
    appId: '1:422371067726:ios:159dc5102a723dc4ed001f',
    messagingSenderId: '422371067726',
    projectId: 'earthquakealert-8923c',
    databaseURL: 'https://earthquakealert-8923c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'earthquakealert-8923c.firebasestorage.app',
    iosBundleId: 'com.example.geoalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO1I_8iOYD8820Drj31Ks3pmUTEQ3S43k',
    appId: '1:422371067726:web:789e5d238f3441e2ed001f',
    messagingSenderId: '422371067726',
    projectId: 'earthquakealert-8923c',
    authDomain: 'earthquakealert-8923c.firebaseapp.com',
    databaseURL: 'https://earthquakealert-8923c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'earthquakealert-8923c.firebasestorage.app',
  );
}
